### PR TITLE
Switch to a maintained fork of the kubectl provider

### PR DESCRIPTION
**Pull request by mpepping**
* The alekc/kubectl provider is a maintained fork of gavinbunney/kubectl 
* The alekc/kubectl provider is trusted by both terraform and opentofu

### CODE REVIEW

**Comment by mrclrchtr** [comment]
When i started developing the module, I had to choose between these two providers and decided against the alekc version. 147 stars and a single maintaining person is simply not enough trust for me.

What do you mean by "The alekc/kubectl provider is trusted by both terraform and opentofu"? 
Do you actually mean it supports both?

Anyway, it currently works with givebunny and unless there's a really good reason, I don't think it's necessary to switch.
Are there any good reasons?

**Comment by mpepping** [comment]
@mrclrchtr, thnx for looking in to this. 

The `gavinbunney/kubectl` provider is not trusted by OpenTofu since @gavinbunney has not submitted the providers public key to registry.opentofu.org. The `alekc/kubectl` is trusted by both the Terraform and OpenTofu registries. 

This makes a tofu throw a warning when doing an init on TF code that uses hcloud-talos:

```shell
❯ tofu init -upgrade
[..] 
- Installing gavinbunney/kubectl v1.14.0...
- Installed gavinbunney/kubectl v1.14.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

So this isn't an issue for Terraform, since the public key for gavinbunney/kubectl **is** added to registry.terraform.io. But it does throw a warning when using OpenTofu.

See this GitHub issue for some more context: https://github.com/gavinbunney/terraform-provider-kubectl/issues/294

**Comment by mrclrchtr** [comment]
I see. Unfortunately I can't test right now due to lack of time. Does everything work exactly the same as before?

**Comment by mpepping** [comment]
> I see. Unfortunately I can't test right now due to lack of time. Does everything work exactly the same as before?

Backwards compatible and tested.

**Comment by mrclrchtr** [comment]
Ok, thank you. I am ready to merge the branch.

But currently this is not possible, because of the merge commits I think... not sure why. 

image

Could you rebase the branch again instead of doing merge commits?

**Pull request merged**
