### PR TITLE
feat(cilium): added BPF/XDP and support for encryption

### PR DESCRIPTION
**Pull request by M4t7e**
This PR adds a few Cilium features to improve the network performance and security:
- Enabled eBPF-based host-routing and masquerading
- Enabled XDP Acceleration for LoadBalancer and NodePort
- Added support for Pod-to-Pod traffic encryption in Cilium

**Before:**
```bash
# kubectl exec -n kube-system ds/cilium -- cilium status --verbose
Host Routing: Legacy
Masquerading: IPTables [IPv4: Enabled, IPv6: Disabled]
[...]
KubeProxyReplacement Details:
  XDP Acceleration: Disabled
[...]
Encryption: Disabled
```

**After:**
```bash
# kubectl exec -n kube-system ds/cilium -- cilium status --verbose
Host Routing: BPF
Masquerading: BPF [eth0, eth1] 10.0.16.0/20 [IPv4: Enabled, IPv6: Disabled]
[...]
KubeProxyReplacement Details:
  XDP Acceleration: Native
[...]
Encryption: Wireguard [NodeEncryption: Disabled, cilium_wg0 (Pubkey: 70TbXMoHvbEtRmsvDck+io/bK1M+QA3y2cBczPWou08=, Port: 51871, Peers: 4)]
```
Info: `endpointRoutes` is excluded here due to https://github.com/cilium/cilium/issues/28812. Additionally, this configuration will automatically become the default in one of the upcoming releases of Cilium (https://github.com/cilium/cilium/issues/14955).

Force Cilium to apply changes: `kubectl -n kube-system rollout restart ds/cilium`

### CODE REVIEW

**Comment by mrclrchtr** [comment]
Hi @M4t7e, thank you very much for this PR!

Could you please add a DCO to your commit? (https://github.com/hcloud-talos/terraform-hcloud-talos/pull/34/checks?check_run_id=26549766936)

**Comment by mrclrchtr** [comment]
And maybe we should use `best-effort` for `loadBalancer.acceleration`? 

> acceleration is the option to accelerate service handling via XDP Applicable values can be: disabled (do not use XDP), native (XDP BPF program is run directly out of the networking driver’s early receive path), or best-effort (use native mode XDP acceleration on devices that support it).

**Comment by mrclrchtr** [comment]
I played around with it a bit today. Unfortunately`bpf.masquerade=true` caused  that coredns could no longer connect to external DNS servers... i/o timout. Do you have any experience with this?

**Comment by M4t7e** [comment]
Hi @mrclrchtr, thanks for the review! :slightly_smiling_face: 

> And maybe we should use `best-effort` for `loadBalancer.acceleration`?

XDP should always be supported by Talos and Hetzner VMs but it would also not hurt to use `best-effort` instead. If you prefer that, I can change it.

> I played around with it a bit today. Unfortunatelybpf.masquerade=true caused that coredns could no longer connect to external DNS servers... i/o timout. Do you have any experience with this?

Good catch! It seems the Talos `forwardKubeDNSToHost` feature does not work together with Cilium BPF based routing (enabled by `bpf.masquerade=true`). See: https://github.com/siderolabs/talos/issues/8836
I would rather deactivate `forwardKubeDNSToHost` as it brings just very limited benefits and on the other hand side the BPF based routing is the no 1 selling point and performance boost of Cilium.

> Could you please add a DCO to your commit? (https://github.com/hcloud-talos/terraform-hcloud-talos/pull/34/checks?check_run_id=26549766936)

I'm not very into that DCO stuff as I see it a bit redundant and tbh annoying here on Github. I would also not put any real name or working mail address into it. Additionally many projects interpret it differently and I have seen no definition in this project. From legal/license perspective it means nothing than there is a sign-off in the commit message, whatever that means.

**Comment by mrclrchtr** [comment]
> XDP should always be supported by Talos and Hetzner VMs but it would also not hurt to use `best-effort` instead. If you prefer that, I can change it.

Yes, you are right, we can leave it as is.

> Good catch! It seems the Talos `forwardKubeDNSToHost` feature does not work together with Cilium BPF based routing (enabled by `bpf.masquerade=true`). See: [siderolabs/talos#8836](https://github.com/siderolabs/talos/issues/8836) I would rather deactivate `forwardKubeDNSToHost` as it brings just very limited benefits and on the other hand side the BPF based routing is the no 1 selling point and performance boost of Cilium.

Hmm.. yesterday I also disabled `forwardKubeDNSToHost` because I already thought that was the reason. But then unfortunately there were also i/o timeouts in the direction of the Hetzner DNS server. I could see from the IPs that these were requested. I then even switched to cloudflare DNS server. There were also i/o timeouts.

Maybe I have to try again and restart coredns.

> I'm not very into that DCO stuff as I see it a bit redundant and tbh annoying here on Github. I would also not put any real name or working mail address into it. Additionally many projects interpret it differently and I have seen no definition in this project. From legal/license perspective it means nothing than there is a sign-off in the commit message, whatever that means.

Ok, I think you are right. Maybe I should disable the check.

**Comment by M4t7e** [comment]
> Hmm.. yesterday I also disabled `forwardKubeDNSToHost` because I already thought that was the reason. But then unfortunately there were also i/o timeouts in the direction of the Hetzner DNS server. I could see from the IPs that these were requested. I then even switched to cloudflare DNS server. There were also i/o timeouts.

How did you find the timeouts? I tried to reproduce them, but so far everything looks fine. By the way, are you using a K8s version compatible with Cilium? I think the current default with Talos 1.7 is K8s 1.30, and Cilium 1.15 is not compatible with K8s 1.30. They will add support in the upcoming 1.16 release.

**Comment by mrclrchtr** [comment]
> How did you find the timeouts? I tried to reproduce them, but so far everything looks fine. 

I had timeouts error logs directly in coreDNS.

> By the way, are you using a K8s version compatible with Cilium? I think the current default with Talos 1.7 is K8s 1.30, and Cilium 1.15 is not compatible with K8s 1.30. They will add support in the upcoming 1.16 release.

That's a good point! I wasn't aware of that. Yes, I have an incompatible version... I will test the RC.

I definitely want to merge this PR, but I would like to test further to get more certainty that everything is working.

**Comment by mrclrchtr** [comment]
With cilium 1.16 and k8s 1.30 everything looks good to me. `forwardKubeDNSToHost` seems to work,too. @M4t7e do you have any complaints? Otherwise we can merge.

**Comment by mrclrchtr** [comment]
This configuration has been running for 2 weeks without any problems. That's why I think it looks good. Thanks again!

**Comment by mrclrchtr** [comment]
There were problems again... unfortunately I can't figure out why and how to solve them... I revert to `masquerade: false`

https://github.com/hcloud-talos/terraform-hcloud-talos/commit/b62ce697302f86687b5980d6c8dfc20fb772f251

**Comment by Rhymen** [comment]
What problems did you observe @mrclrchtr? I tried a similar configuration and can still see the timeout logs in coreDNS.

**Comment by mrclrchtr** [comment]
Yes I observed the timeout logs 😕

**Pull request merged**
